# Generated by Django 6.0.4 on 2026-04-22 16:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã sản phẩm')),
                ('name', models.CharField(max_length=255, verbose_name='Tên sản phẩm')),
                ('brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='Thương hiệu')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Hình ảnh')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('type', models.CharField(max_length=100, verbose_name='Loại giày')),
                ('subtype', models.CharField(blank=True, max_length=100, null=True, verbose_name='Phân loại phụ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sản phẩm',
                'verbose_name_plural': 'Sản phẩm',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên nhà cung cấp')),
                ('phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Địa chỉ')),
            ],
            options={
                'verbose_name': 'Nhà cung cấp',
                'verbose_name_plural': 'Nhà cung cấp',
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50, verbose_name='Màu sắc')),
                ('size', models.CharField(max_length=20, verbose_name='Kích thước')),
                ('import_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Giá nhập')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Giá bán')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='SKU')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='Số lượng tồn')),
                ('min_quantity', models.IntegerField(default=5, verbose_name='Tồn tối thiểu')),
                ('is_active', models.BooleanField(default=True, verbose_name='Cho phép bán')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='management.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Biến thể sản phẩm',
                'verbose_name_plural': 'Biến thể sản phẩm',
                'unique_together': {('product', 'color', 'size')},
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã đơn nhập')),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày nhập')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Tổng tiền')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('status', models.CharField(choices=[('waiting', 'Đang chờ'), ('finished', 'Hoàn thành'), ('canceled', 'Đã hủy')], default='waiting', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.supplier', verbose_name='Nhà cung cấp')),
            ],
            options={
                'verbose_name': 'Đơn nhập hàng',
                'verbose_name_plural': 'Đơn nhập hàng',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Số lượng')),
                ('actual_import_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Giá nhập thực tế')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='management.purchaseorder')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.productvariant')),
            ],
            options={
                'verbose_name': 'Chi tiết đơn nhập',
                'verbose_name_plural': 'Chi tiết đơn nhập',
            },
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã hóa đơn')),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên khách hàng')),
                ('customer_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='SĐT khách hàng')),
                ('sale_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày bán')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Tổng cộng')),
                ('payment_method', models.CharField(choices=[('cash', 'Tiền mặt'), ('transfer', 'Chuyển khoản')], max_length=20, verbose_name='Phương thức thanh toán')),
                ('payment_status', models.CharField(choices=[('finished', 'Đã thanh toán'), ('owe', 'Còn nợ')], default='finished', max_length=20, verbose_name='Trạng thái thanh toán')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Người bán')),
            ],
            options={
                'verbose_name': 'Hóa đơn bán hàng',
                'verbose_name_plural': 'Hóa đơn bán hàng',
            },
        ),
        migrations.CreateModel(
            name='SalesOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Số lượng')),
                ('selling_price_at_time', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Giá bán lúc đó')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='management.salesorder')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.productvariant')),
            ],
            options={
                'verbose_name': 'Chi tiết hóa đơn',
                'verbose_name_plural': 'Chi tiết hóa đơn',
            },
        ),
    ]
